# Configuration specific to Admin BackOffice Service
server:
  port: 8084

spring:
  application:
    name: admin-backoffice-service
  datasource:
    # H2 Configuration for development
    url: jdbc:h2:mem:admin_backoffice_db
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

# Admin-specific Configuration
admin:
  session:
    timeout: 3600000  # 1 hour
  audit:
    enabled: true
    retention-days: 90
