# Default configuration for all services
spring:
  datasource:
    # Default H2 configuration for development
    url: jdbc:h2:mem:bookstore_db
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000  # 24 hours
  refresh-expiration: 604800000  # 7 days

# CORS Configuration
cors:
  allowed-origins: http://localhost:4200,http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

# Logging Configuration
logging:
  level:
    com.bookstore: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
