# Configuration specific to Book Catalogue Service
server:
  port: 8082

spring:
  application:
    name: book-catalogue-service
  datasource:
    # MySQL Configuration for production
    url: jdbc:mysql://localhost:3306/catlog_schema
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

# Book-specific Configuration
books:
  pagination:
    default-size: 20
    max-size: 100
  search:
    enabled: true
    index-refresh-interval: 300000  # 5 minutes
