
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { CategoryService } from '../../../services/category.service';
import { CategoryModel } from '../../../models/category.model';

@Component({
  selector: 'app-category-management',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './category-management.component.html',
  styleUrls: ['./category-management.component.css']
})
export class CategoryManagementComponent implements OnInit {
  categories: CategoryModel[] = [];
  
  // Form fields
  newCategory: CategoryModel = {
    id: '',
    name: '',
    slug: '',
    description: '',
    image: '',
    displayOrder: 0,
    isActive: true
  };
  
  // Edit mode
  editingCategory: CategoryModel | null = null;
  editForm: CategoryModel = {
    id: '',
    name: '',
    slug: '',
    description: '',
    image: '',
    displayOrder: 0,
    isActive: true
  };
  
  // UI state
  isLoading: boolean = false;
  errorMessage: string | null = null;
  successMessage: string | null = null;
  categoryInputError: boolean = false;

  constructor(private categoryService: CategoryService, private router: Router) { }

  ngOnInit(): void {
    this.fetchCategories();
  }

  fetchCategories(): void {
    this.isLoading = true;
    this.errorMessage = null;
    this.successMessage = null;
    
    this.categoryService.getAllCategories().subscribe({
      next: (data: CategoryModel[]) => {
        // Sort by displayOrder for better UX
        this.categories = data.sort((a, b) => (a.displayOrder || 0) - (b.displayOrder || 0));
        this.isLoading = false;
      },
      error: (error: any) => {
        console.error('Error fetching categories:', error);
        this.errorMessage = 'Failed to load categories.';
        this.isLoading = false;
      }
    });
  }

  onAddCategory(): void {
    // Validate category name
    if (!this.newCategory.name || !this.newCategory.name.trim()) {
      this.categoryInputError = true;
      this.errorMessage = 'Category name cannot be empty.';
      this.clearMessagesAfterDelay(3000, true);
      return;
    }

    if (this.newCategory.name.trim().length < 2) {
      this.categoryInputError = true;
      this.errorMessage = 'Category name must be at least 2 characters long.';
      this.clearMessagesAfterDelay(3000, true);
      return;
    }

    // Check if category already exists
    const existingCategory = this.categories.find(cat => 
      cat.name.toLowerCase() === this.newCategory.name.trim().toLowerCase()
    );

    if (existingCategory) {
      this.categoryInputError = true;
      this.errorMessage = 'Category with this name already exists.';
      this.clearMessagesAfterDelay(3000, true);
      return;
    }

    this.categoryInputError = false;
    this.isLoading = true;
    this.errorMessage = null;
    this.successMessage = null;

    // Prepare category payload (slug will be auto-generated by backend)
    const categoryPayload: CategoryModel = {
      id: '', // Backend will generate
      name: this.newCategory.name.trim(),
      description: this.newCategory.description?.trim() || '',
      displayOrder: this.newCategory.displayOrder || 0,
      isActive: this.newCategory.isActive !== false // Default to true
    };

    this.categoryService.createCategory(categoryPayload).subscribe({
      next: (createdCategory: CategoryModel) => {
        this.categories.push(createdCategory);
        // Re-sort categories
        this.categories = this.categories.sort((a, b) => (a.displayOrder || 0) - (b.displayOrder || 0));
        this.resetNewCategoryForm();
        this.successMessage = 'Category added successfully!';
        this.isLoading = false;
        this.clearMessagesAfterDelay();
      },
      error: (error: any) => {
        console.error('Error creating category:', error);
        this.errorMessage = 'Failed to create category. Please try again.';
        this.isLoading = false;
        this.clearMessagesAfterDelay(3000, true);
      }
    });
  }

  onEdit(category: CategoryModel): void {
    this.editingCategory = category;
    this.editForm = { ...category }; // Create a copy
    this.errorMessage = null;
    this.successMessage = null;
  }

  onSaveEdit(): void {
    if (!this.editingCategory || !this.editForm.name || !this.editForm.name.trim()) {
      this.errorMessage = 'Category name cannot be empty.';
      this.clearMessagesAfterDelay(3000, true);
      return;
    }

    if (this.editForm.name.trim().length < 2) {
      this.errorMessage = 'Category name must be at least 2 characters long.';
      this.clearMessagesAfterDelay(3000, true);
      return;
    }

    // Check for duplicate name (excluding current category)
    const existingCategory = this.categories.find(cat => 
      cat.id !== this.editingCategory!.id && 
      cat.name.toLowerCase() === this.editForm.name.trim().toLowerCase()
    );

    if (existingCategory) {
      this.errorMessage = 'Another category with this name already exists.';
      this.clearMessagesAfterDelay(3000, true);
      return;
    }

    this.isLoading = true;
    this.errorMessage = null;
    this.successMessage = null;

    // Prepare update payload
    const updatePayload: CategoryModel = {
      ...this.editForm,
      name: this.editForm.name.trim(),
      description: this.editForm.description?.trim() || ''
    };

    this.categoryService.updateCategory(this.editingCategory.id, updatePayload).subscribe({
      next: (updatedCategory: CategoryModel) => {
        // Update the category in the list
        const index = this.categories.findIndex(cat => cat.id === updatedCategory.id);
        if (index !== -1) {
          this.categories[index] = updatedCategory;
          // Re-sort categories
          this.categories = this.categories.sort((a, b) => (a.displayOrder || 0) - (b.displayOrder || 0));
        }
        this.cancelEdit();
        this.successMessage = 'Category updated successfully!';
        this.isLoading = false;
        this.clearMessagesAfterDelay();
      },
      error: (error: any) => {
        console.error('Error updating category:', error);
        this.errorMessage = 'Failed to update category. Please try again.';
        this.isLoading = false;
        this.clearMessagesAfterDelay(3000, true);
      }
    });
  }

  cancelEdit(): void {
    this.editingCategory = null;
    this.editForm = {
      id: '',
      name: '',
      slug: '',
      description: '',
      image: '',
      displayOrder: 0,
      isActive: true
    };
  }

  onToggleActive(category: CategoryModel): void {
    this.isLoading = true;
    this.errorMessage = null;
    this.successMessage = null;

    this.categoryService.toggleCategoryActiveStatus(category.id).subscribe({
      next: (updatedCategory: CategoryModel) => {
        // Update the category in the list
        const index = this.categories.findIndex(cat => cat.id === updatedCategory.id);
        if (index !== -1) {
          this.categories[index] = updatedCategory;
        }
        this.successMessage = `Category ${updatedCategory.isActive ? 'activated' : 'deactivated'} successfully!`;
        this.isLoading = false;
        this.clearMessagesAfterDelay();
      },
      error: (error: any) => {
        console.error('Error toggling category status:', error);
        this.errorMessage = 'Failed to update category status. Please try again.';
        this.isLoading = false;
        this.clearMessagesAfterDelay(3000, true);
      }
    });
  }

  onDelete(category: CategoryModel): void { 
    if (confirm(`Are you sure you want to delete the category "${category.name}"? This cannot be undone.`)) {
      this.isLoading = true;
      this.errorMessage = null;
      this.successMessage = null;

      this.categoryService.deleteCategory(category.id).subscribe({
        next: () => {
          this.categories = this.categories.filter(c => c.id !== category.id);
          this.successMessage = 'Category deleted successfully!';
          this.isLoading = false;
          this.clearMessagesAfterDelay();
        },
        error: (error: any) => {
          console.error('Error deleting category:', error);
          this.errorMessage = 'Failed to delete category. Please try again.';
          this.isLoading = false;
          this.clearMessagesAfterDelay(3000, true);
        }
      });
    }
  }

  resetNewCategoryForm(): void {
    this.newCategory = {
      id: '',
      name: '',
      slug: '',
      description: '',
      image: '',
      displayOrder: 0,
      isActive: true
    };
    this.categoryInputError = false;
  }

  clearMessagesAfterDelay(delay: number = 3000, isError: boolean = false): void {
    setTimeout(() => {
      if (isError) {
        this.errorMessage = null;
      } else {
        this.successMessage = null;
      }
      this.isLoading = false;
    }, delay);
  }

  goBack(): void {
    this.router.navigate(['/admin-main']);
  }
}
